Pass loop to ResponseHandler for aiohttp 4
This is required since
https://github.com/aio-libs/aiohttp/commit/6b0bc4ef9365d855ad9dbd293dfbed576a784c16.

Fixes:

    tests/test_aioresponses.py:266: in test_address_as_instance_of_url_combined_with_pass_through
        api, ext = yield from doit()
    tests/test_aioresponses.py:258: in doit
        api_resp = yield from self.session.get(self.url)
    aioresponses/core.py:328: in _request_mock
        response = await self.match(method, url, **kwargs)
    aioresponses/core.py:304: in match
        response = await matcher.build_response(url, **kwargs)
    aioresponses/core.py:184: in build_response
        reason=result.reason)
    aioresponses/core.py:157: in _build_response
        resp.content = stream_reader_factory()
    aioresponses/compat.py:26: in stream_reader_factory
        protocol = ResponseHandler(loop=loop)
    ../aiohttp/aiohttp/client_proto.py:41: in __init__
        self.closed = self._loop.create_future()  # type: asyncio.Future[None]
    E   AttributeError: 'NoneType' object has no attribute 'create_future'

Ref: https://github.com/aio-libs/aiohttp/pull/3733