Remove remnants of aiohttp 2.x and Python 3.5 support
Commit adfb65038caebce3d62 removed support for aiohttp 2.x and Python
3.5 but there are still some remnants of these left. We get rid of them.
This also removes one `mypy` warning:

> compat.py:31: error: All conditional function variants must have identical signatures [misc]