Don't test with aiohttp 3.6 and older on Python 3.10
aiohttp 3.6 and older use Python features which were removed in Python
3.10:

                assert port is not None
    >           hosts = await asyncio.shield(self._resolve_host(
                    host,
                    port,
                    traces=traces), loop=self._loop)
    E               TypeError: shield() got an unexpected keyword argument 'loop'

    .tox/py3.10-aiohttp35/lib/python3.10/site-packages/aiohttp/connector.py:952: TypeError

To avoid test failures, we remove unsupported combinations from GitHub
workflows.